DEPOSIT = "DEPOSIT"
WITHDRAWAL = "WITHDRAWAL"
LOAN = "LOAN"
LOAN_PAID ="LOAN_PAID"

TRANSACTION_TYPE_CHOICE =(
    (DEPOSIT,"DEPOSIT"),
    (WITHDRAWAL,"WITHDRAWAL"),
    (LOAN,"LOAN"),
    (LOAN_PAID,"LOAN_PAID"),
)