# Generated by Django 4.2.1 on 2023-06-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='initial_deposite_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
