# Generated by Django 4.2.2 on 2023-06-24 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='loan_approved',
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Transactions.transaction')),
                ('loan_approved', models.BooleanField(default=False)),
            ],
            bases=('Transactions.transaction',),
        ),
    ]
